package mtasa.enums;

@:enum abstract WeaponSlot(Int) {
  var WEAPONSLOT_TYPE_UNARMED = 0;
  var WEAPONSLOT_TYPE_MELEE = 1;
  var WEAPONSLOT_TYPE_HANDGUN = 2;
  var WEAPONSLOT_TYPE_SHOTGUN = 3;
  var WEAPONSLOT_TYPE_SMG = 4;
  var WEAPONSLOT_TYPE_RIFLE = 5;
  var WEAPONSLOT_TYPE_SNIPER = 6;
  var WEAPONSLOT_TYPE_HEAVY = 7;
  var WEAPONSLOT_TYPE_THROWN = 8;
  var WEAPONSLOT_TYPE_SPECIAL = 9;
  var WEAPONSLOT_TYPE_GIFT = 10;
  var WEAPONSLOT_TYPE_PARACHUTE = 11;
  var WEAPONSLOT_TYPE_DETONATOR = 12;
}