name: Publish to Haxelib repository

on:
  push:
    branches: [ master ]

jobs:
  publish_to_haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ianharrigan/GitHubActionsTest/.github/actions/haxe@master
        with:
          haxe-version: [4.0.5]
      - run: haxelib submit
